/**
 * Central image registry. Every photograph used on the site is declared here —
 * components reference images by key and never hard-code paths or URLs.
 *
 * Files are served from /public/images (downloaded and optimised from their
 * public sources so the site never depends on third-party hotlinks).
 * `source` records where each photo came from for attribution (see /credits).
 *
 * To use the client's own stockyard photography, add the files to
 * /public/images/stockyard, register them here and list them in
 * `stockyardGallery` at the bottom of this file.
 */

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  /** Tiny WebP used as the blur-up placeholder while the full image loads. */
  blur: string;
  source: { name: string; url: string; author?: string; license: string };
};

const unsplash = (id: string) => ({
  name: "Unsplash",
  url: `https://images.unsplash.com/photo-${id}`,
  license: "Unsplash License",
});

export const images = {
  heroSteelPlantSunrise: {
    src: "/images/hero-steel-plant-sunrise.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAgAA4BaJaACdAEf5hcqhAAA/vCZ+xivFi0J8+0Wahv79d45tMkEATcNmWil3vEkEZrM1Qsx6CO5Cf1yq6AA",
    alt: "Steel plant silhouetted against a golden sunrise",
    source: unsplash("1765810542186-c6becc0687b1"),
  },
  bridgeArchIndia: {
    src: "/images/bridge-arch-india.webp",
    width: 1920,
    height: 1080,
    blur: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoMAAcAA4BaJaACdADZlONAAP7tTFP4OoFfVV5CWtsEnX5pL/KFNFFnyJyEZbq48kg0MExo3vC2pQADCO0wreOLJF2KQCFhIAA=",
    alt: "Steel arch railway bridge spanning a wide river in India",
    source: unsplash("1705575468304-de4fb558a575"),
  },
  bridgeTrussCloseup: {
    src: "/images/bridge-truss-closeup.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoMAAgAA4BaJQBdgBu0KjHgAOJ/p87/JCz06/2r1OxLTtvlr6PeAEn7kFR13k1NveGeozfz2KVqc2rGsuOdDscbUAA=",
    alt: "Close view of riveted steel truss members on a bridge",
    source: unsplash("1747057072654-fe8b363e58ab"),
  },
  bridgeHowrah: {
    src: "/images/bridge-howrah.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoMAAgAA4BaJZQAAueMWBaQAP6MPA+YBJ1ojXZAAAA=",
    alt: "Howrah Bridge cantilever steel truss over the Hooghly river in mist",
    source: unsplash("1770020726940-6fd69bf40aaa"),
  },
  bridgeRailTruss: {
    src: "/images/bridge-rail-truss.webp",
    width: 1920,
    height: 1277,
    blur: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoMAAgAA4BaJZwAAkrMHAAA/t1vYAfMWDm6rPya+0GevInn9U81UX/xtV/SNNwMHO+LdYAA",
    alt: "Train crossing a steel truss bridge over water",
    source: unsplash("1785768275074-d6e34781c6f1"),
  },
  pipesRustyStack: {
    src: "/images/pipes-rusty-stack.webp",
    width: 1920,
    height: 1440,
    blur: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAkAA4BaJZwC7AEPeu279QAA/veFQHMkDPs35/QNj6uUmtqs3yHGY/R9d+MKYT3rovDIm6LAAA==",
    alt: "Stack of mild steel round pipes viewed from the ends",
    source: unsplash("1721622045835-51a5447f281c"),
  },
  pipesBlackStack: {
    src: "/images/pipes-black-stack.webp",
    width: 1920,
    height: 2560,
    blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoMABAAA4BaJYwCdAEQzZYUpoCFAAD+9flpIoWcHLIwlxzY8Ayvy/XJ0cWZ//7Hs8KFTJRW5GAvir/AfMqIT7Gv9aT1/AbfGNwfRKvUZcUdKfJLgzpD2xnOuAAAAA==",
    alt: "Bundle of black steel pipes stacked end-on",
    source: unsplash("1647105604066-86ea4247e217"),
  },
  pipesBlackEnds: {
    src: "/images/pipes-black-ends.webp",
    width: 1920,
    height: 2560,
    blur: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAAAwAQCdASoMABAAA4BaJaQAA3AA/vQkz6g9CZnpYFyObJyUKcQih0FAAAA=",
    alt: "Close-up of black steel pipe ends in a stack",
    source: unsplash("1721622045796-d7dd41ef5788"),
  },
  tubesStainlessLine: {
    src: "/images/tubes-stainless-line.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAgAA4BaJZwAD43wxSTFU4AA/ms4q8vCBRjNsXtrxpAvCD5ax1gOr+KRoqKN9dX80BBVcKQcMuymYSCN51gmRhAAAA==",
    alt: "Bright steel tubes bundled on a production line",
    source: unsplash("1764835746713-34a671e73569"),
  },
  pipesGalvanized: {
    src: "/images/pipes-galvanized.webp",
    width: 1920,
    height: 2880,
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoMABIAPu1iqU2ppaQiMAgBMB2JZwC/OCHWnJ4AVLAAAM14tZ3BqBmiBmzjC3s3O8uvKsZuCKIAAtHOxnwZxNOMELwWlEb3VNvFNO8Dejs1xvGJJWtEAA==",
    alt: "Galvanised steel pipes stacked on a rack",
    source: unsplash("1520697517317-6767553cc51a"),
  },
  tmtBarsStack: {
    src: "/images/tmt-bars-stack.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAgAA4BaJaACdLoAAwga4SAA8mhu32GqumcoRspGu+vKfE23kUixeAAAAA==",
    alt: "Ribbed TMT reinforcement bars stacked horizontally",
    source: unsplash("1745909247906-123b53b70e06"),
  },
  tmtCoils: {
    src: "/images/tmt-coils.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAgAA4BaJZQC7AELKUrXAAD+6fYgE1xmcrYN4u7DdWz2UGuHPY2juH/nO/kdXYndKsQAAAA=",
    alt: "Coiled ribbed reinforcement bars bundled for delivery",
    source: unsplash("1763771420746-c75fefab51b5"),
  },
  tmtCoils2: {
    src: "/images/tmt-coils-2.webp",
    width: 1920,
    height: 1240,
    blur: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAgAA4BaJYwCdAEQ+Q27kAD+5D9lrOPbpdMuD9aaebHHVCI/Zi7xMUy/N4Nxfy7BmAAA",
    alt: "Bundled coils of ribbed reinforcement steel",
    source: unsplash("1763771420303-0f11ccf613d1"),
  },
  tmtBundleField: {
    src: "/images/tmt-bundle-field.webp",
    width: 1920,
    height: 1317,
    blur: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgAA4BaJYgCdAEUPkgCAAD+wFipL9/72cW+v2XqleWsMEaUoiB/ntr5mccOXhhLMY8axhNNSYO5YqcAAA==",
    alt: "Bundles of reinforcement bars stored on site",
    source: unsplash("1755289832483-c633ada42a8c"),
  },
  roundBarsFactory: {
    src: "/images/round-bars-factory.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoMAAgAA4BaJZQAAlr0kI2wAP7eIJvFaxhjeCDNj8Fb5QawPL7DmaDEom5oPtCOkigWXDlqHTxRUz74zc9/NhnfgAA=",
    alt: "Bundles of solid steel round bars in a factory",
    source: unsplash("1671404910386-8c2a9ae40efd"),
  },
  rodsRust: {
    src: "/images/rods-rust.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoMAAgAA4BaJYwC7ADWvEAA/uyMrwuoRzfh/fXS8gfmR8tAAAA=",
    alt: "Steel rods arranged in a dense bundle",
    source: unsplash("1623428454598-1bfe414bac03"),
  },
  structuralSectionsWarehouse: {
    src: "/images/structural-sections-warehouse.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAgAA4BaJZwAApytfG5EAAD+u1d5rCQJwggQTyOQEZOS4AXoArgheKiaChBeViMIiPgIAAA=",
    alt: "Structural steel sections, channels and tubes stacked in a warehouse",
    source: unsplash("1671022442106-c787685d9fed"),
  },
  beamsRoofFrame: {
    src: "/images/beams-roof-frame.webp",
    width: 1920,
    height: 2037,
    blur: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAQCdASoMAA0AA4BaJZwAApebVIkAAP72lC5Eapx+QxbuGmXD9HbC92aU6XfTnW5QrgtWUkgPljMFPKthIJh4XwSLQhS3QK4x6em554MTLOOuZwOAAA==",
    alt: "Steel beams forming a modern roof frame",
    source: unsplash("1745162391671-244e8d3ccd5f"),
  },
  trussBlue: {
    src: "/images/truss-blue.webp",
    width: 1920,
    height: 2880,
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoMABIAPu1iqU2ppaOiMAgBMB2JZgCdMoADZC6OfRUgOn9RgAD+2hnD8IcHhA5rmEZwygFqh1u7ko3mhCiJZJFnM+qaA4lppzPse5NmcxTlC1KaPhv7L1MG9E+UJBLV+be0swuaAAA=",
    alt: "Painted steel truss framework seen from below",
    source: unsplash("1507486076008-3c60cfcce36f"),
  },
  steelGridSky: {
    src: "/images/steel-grid-sky.webp",
    width: 1920,
    height: 1080,
    blur: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAcAA4BaJZQCdADcpPQBBcAA+LMc195l1X8HzCNNPOsqnGnGFSIyqaVKBcXhelVjzo3AcNYulLRm3slQAA==",
    alt: "Steel structural grid against a pale sky",
    source: unsplash("1509024368907-57294758cfc5"),
  },
  steelRoofGrid: {
    src: "/images/steel-roof-grid.webp",
    width: 1920,
    height: 1371,
    blur: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoMAAkAA4BaJZwAAupmGHAAAP6Pt+OZTC37Ww9Er0VhuDGuCTk+H91f/sF3HgJBMDSUxjZxluMqB0SGAAA=",
    alt: "Steel roof grid with bracing seen from below",
    source: unsplash("1724814884431-5f931c9620ae"),
  },
  steelFrameCranes: {
    src: "/images/steel-frame-cranes.webp",
    width: 1920,
    height: 2880,
    blur: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoMABIAPu1kq04ppaQiMAgBMB2JZQC7ACHhTMwUGEFgOAD+w4XqzuUaFw6hGA16xfzOunV9UguhvEQ+6Nvz/1IMw9yIx7Kh0Dk8AA==",
    alt: "Steel building frame under construction with tower cranes",
    source: unsplash("1527335988388-b40ee248d80c"),
  },
  coilsWarehouse: {
    src: "/images/coils-warehouse.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAgAA4BaJaQAAuySMvocnQAA/vNfGnMzz+HkVLsODSAwuASczK9Ukhy3wcIZr/bSznTYJgruZz0bo8AAAA==",
    alt: "Rows of steel coils in a warehouse",
    source: unsplash("1697698532634-ea59b636ccea"),
  },
  coilsCloseup: {
    src: "/images/coils-closeup.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoMAAgAA4BaJaQAAlxjJ5wAAP70V8ZkrhxOCy7XokUx9jO36y1BBC5H82yrhz8hAe6r8PBvIkgAAA==",
    alt: "Close-up of rolled steel coils",
    source: unsplash("1697698532602-ccf880036281"),
  },
  sheetsCoatedStack: {
    src: "/images/sheets-coated-stack.webp",
    width: 1920,
    height: 1080,
    blur: "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoMAAcAA4BaJZwAAxS48ftpFpAAAPwqG1/4mWzvH40mX4/Nc3aHgJC9qAbQq88HMAFwAA==",
    alt: "Stack of coated steel sheets",
    source: unsplash("1761434558206-2deda18ef237"),
  },
  stainlessBrushed: {
    src: "/images/stainless-brushed.webp",
    width: 1920,
    height: 1920,
    blur: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAwAA4BaJZQC7ADdr2K7j4AA/uf0EhKpNqJeeXqCfMrVYO6oM8MTR4AAAA==",
    alt: "Brushed stainless steel surface with light reflection",
    source: unsplash("1667892702884-faa077e80d7b"),
  },
  chequeredPlate: {
    src: "/images/chequered-plate.webp",
    width: 1920,
    height: 1078,
    blur: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoMAAcAA4BaJZQCdADGCcQAAMwCMSrlRWHTOdOcyFCzptaEAAA=",
    alt: "Chequered steel plate with raised pattern",
    source: unsplash("1501166222995-ff31c7e93cef"),
  },
  chequeredPlate2: {
    src: "/images/chequered-plate-2.webp",
    width: 1920,
    height: 1087,
    blur: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoMAAcAA4BaJYwCdADDf7ogAOCPglDBzFTEYZ+rwAA=",
    alt: "Diamond pattern steel floor plate",
    source: unsplash("1775204450608-3afe112ae5f8"),
  },
  corrugatedSheet: {
    src: "/images/corrugated-sheet.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoMAAgAA4BaJaQAAp1H1X8AAP7fZbRH45g7slaxNIAAAA==",
    alt: "Corrugated galvanised steel sheet",
    source: unsplash("1533069174012-17e2fefc8e2a"),
  },
  corrugatedShed: {
    src: "/images/corrugated-shed.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAgAA4BaJZwAAq9eElbZSAAA/odzVBXXcne93QbAALmE7DELUaAYV1IUKWP6mAObJbnEgFAAAA==",
    alt: "Industrial shed clad in corrugated metal sheets",
    source: unsplash("1450851100967-1a8368a583c4"),
  },
  roofColourCoated: {
    src: "/images/roof-colour-coated.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAgAA4BaJbACdADdkHjigAD33Ky4XSYdn9p1PAAs4lM+a04W3sgWBjdZjwKxQdDctbG/OG5wG1cmWzAAAAAA",
    alt: "Colour coated metal roof of an industrial building",
    source: unsplash("1776653244534-69d59028af6c"),
  },
  roofStandingSeam: {
    src: "/images/roof-standing-seam.webp",
    width: 1920,
    height: 1282,
    blur: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAgAA4BaJaQAAuX52dWGAAD+63iWveCx1NCYPtZtbTF7q110rIfNims+qN6IAfQtxrDgAAA=",
    alt: "Dark profiled metal roofing on a modern building",
    source: unsplash("1602193230480-7840a38eb0c3"),
  },
  stockRacksBars: {
    src: "/images/stock-racks-bars.webp",
    width: 1920,
    height: 1098,
    blur: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoMAAcAA4BaJQBdgBuhnZfQAP7ytWeKpjCu+qRUn9DTgyIYQirk88kgAAA=",
    alt: "Steel bars and flats stored on stockyard racks",
    source: unsplash("1763926025477-423847028860"),
  },
  stockRacksBarsTall: {
    src: "/images/stock-racks-bars-tall.webp",
    width: 1920,
    height: 2880,
    blur: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoMABIAPu1iqU2ppaOiMAgBMB2JZwC7ABt9pBM8HzCTVjY4AAD+iQunCAtNiIaVZDpPsuyqbUckCvs0Dy7azfaYSwMTmB+wkljFeQzKBXynRTriuTvx9yoy0HFhiyCXZ30PoKxE9PVvVhnxiY09Y5DHagAAAA==",
    alt: "Tall steel racks loaded with bars in a stockyard",
    source: unsplash("1763926025678-95d196d0ab28"),
  },
  stockRacksFlats: {
    src: "/images/stock-racks-flats.webp",
    width: 1920,
    height: 2547,
    blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMABAAA4BaJYgCdAEf3aaZgpHTmAAA/onIMVJN8z4Ne1IUM29WpcBhd2TvuEmM0USifaHE4m9yAcAFzqu/dd3RoK0HZNs0Ij6ZAlTmEM3eFQUtWcVFjKnzuDOAAA==",
    alt: "Stockyard racks holding steel flats and bars",
    source: unsplash("1763926025680-7966e45e48f5"),
  },
  stockRacksMono: {
    src: "/images/stock-racks-mono.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAgAA4BaJaQAAxamHq2z4AD+75bS9gXKi1Odr5N9qdcycsK2PeXXF8ymKGIAAAA=",
    alt: "Steel bars and sections neatly stacked on warehouse racks",
    source: unsplash("1763926062529-1edf8664c366"),
  },
  warehouseModern: {
    src: "/images/warehouse-modern.webp",
    width: 1920,
    height: 1281,
    blur: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAgAA4BaJZQC7AD7uE4W1AD98HaXezyNeygPi6ahYbuK2t39soHIcI/8kjx1vFAaqxBXy4xReAAA",
    alt: "Large modern industrial warehouse interior",
    source: unsplash("1772305336606-989a457ffbae"),
  },
  sheetProcessingLine: {
    src: "/images/sheet-processing-line.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAgAA4BaJZwAAsaGD7TeIAD4178GJQgSpgdGHYCs4N9yzqoVIlHiTUpmflzygfxSo8IA",
    alt: "Steel sheet processing line inside a factory",
    source: unsplash("1764835994645-3faa2c40f708"),
  },
  factoryLine: {
    src: "/images/factory-line.webp",
    width: 1920,
    height: 1281,
    blur: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMAAgAA4BaJZACdADcVsIhAAAA+6WrVIT2JRzumhCO2qNWGRm0KPOokTYCoDqQq9aI+aGdYAA=",
    alt: "Industrial machinery inside a large factory",
    source: unsplash("1717386255773-1e3037c81788"),
  },
  blastFurnace: {
    src: "/images/blast-furnace.webp",
    width: 1920,
    height: 1080,
    blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoMAAcAA4BaJYwCdH8AgmCZ5dkHAAD+2BtTuA59zAJyQbAcLiWU/1ufzg6JOj9Bz7wCTBs5ID9HWGBjVx/reooTTwaWRwAA",
    alt: "Blast furnace structures of a steel plant",
    source: unsplash("1787285724892-38c3cb5fbbdb"),
  },
  weldingSparks: {
    src: "/images/welding-sparks.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoMAAgAA4BaJQBOgBuTXtKkgAD+8wlrifQvKvg1jQ/+lsj8hZnATHtGyy2goN4rIZwXz7PN1ljJoJfOom4Wy/SbRsDQgAAA",
    alt: "Welder working on steel with sparks",
    source: unsplash("1504328345606-18bbc8c9d7d1"),
  },
  weldingBlue: {
    src: "/images/welding-blue.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAAgAA4BaJagCdAEDesILZAAA/vLi+T2NNHK3BzQLyA9Ghp8ZD245uUCOIGumDShJTtViAIv2DaC8j2aPQkxCoOEZOs1i2AAAAA==",
    alt: "Welder fabricating steel under blue arc light",
    source: unsplash("1455165814004-1126a7199f9b"),
  },
  fabricationCutting: {
    src: "/images/fabrication-cutting.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgAA4BaJZACdADRT6PvAAD+9Z2yHYR3AfN2h3/bp3au1rHoC8eqMmaWR3Sa1DM9f+8NWvxIuU0N0mwAAA==",
    alt: "Fabricator cutting square steel tubes with sparks",
    source: unsplash("1714504904786-b6732390b206"),
  },
  wireCoilDark: {
    src: "/images/wire-coil-dark.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAgAA4BaJZwCw7EPAldH3cAA/tvREUVFI2s8g13iCYsDV+VNHJzGkgAAAA==",
    alt: "Coil of steel wire on a floor",
    source: unsplash("1673201159819-f842efcfdf13"),
  },
  wireCoilsGi: {
    src: "/images/wire-coils-gi.webp",
    width: 1920,
    height: 1536,
    blur: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAoAA4BaJZwAAmb4Q9AAAPtvLn3h9E1yuSaKFp6FSYOuqhf6AZLdVODrwDScmtHVOzFQNg3wIAAA",
    alt: "Coils of galvanised steel wire",
    source: unsplash("1518994255497-c5f17690567f"),
  },
  railTrackIndia: {
    src: "/images/rail-track-india.webp",
    width: 1920,
    height: 2580,
    blur: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMABAAA4BaJaQAAlriVOksy6AA/vQJqMxo4doE/FE1llLuM3EzjJoztXT+4balc4sjXkgkx4NoCAMuq9L4IAAA",
    alt: "Railway tracks with overhead electrification in India",
    source: unsplash("1610611342266-bcc131ecc78c"),
  },
  railTrack: {
    src: "/images/rail-track.webp",
    width: 1920,
    height: 1282,
    blur: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAgCdASoMAAgAA4BaJZACdGuAAs1oxVaIwAD+ZrFI5yT3eKeGFezmznpbAJQddiqAHlXySbxDJf5BEmiAoYsHAvU2HAAA",
    alt: "Steel railway rails stretching into the distance",
    source: unsplash("1622504789958-449b1f7a12c0"),
  },
  cranesSunset: {
    src: "/images/cranes-sunset.webp",
    width: 1920,
    height: 1275,
    blur: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAAgAA4BaJZACdADzxqmQAAD+hAV0T3cSR5moz03dVCpHBgA1En1XKyWzCdstjWEysWP9YnNRUUs7wAA=",
    alt: "Tower cranes silhouetted against a dusk sky",
    source: unsplash("1575230167650-dce335edc7f4"),
  },
  constructionIndiaTowers: {
    src: "/images/construction-india-towers.webp",
    width: 1920,
    height: 1916,
    blur: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoMAAwAA4BaJYgCdAEO5FmUpTggAP701B7idiFUHx5iZ/Krk02atw6cnAtSYMTO3PocVNKyNTm4uhbq0HFl+WgpK0AAAA==",
    alt: "Residential towers under construction in an Indian city",
    source: unsplash("1630061712710-2539eb457c55"),
  },
  constructionIndiaScaffold: {
    src: "/images/construction-india-scaffold.webp",
    width: 1920,
    height: 1080,
    blur: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAcAA4BaJQBOgB0/PBUDLbgA/rbMdQiFvZATkII4BuCSEWIrLi/4iluIkMYw2FjzWaPTYx2fGJwKge6gAAAA",
    alt: "Building under construction with scaffolding",
    source: unsplash("1747192904662-e03e8da1e0ab"),
  },
  constructionIndiaHighrise: {
    src: "/images/construction-india-highrise.webp",
    width: 1920,
    height: 2547,
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoMABAAA4BaJZgCdH8AE7EYIIWUAAD+8jh4wu5oZyZlIzkHRYxT5Exq9PIv8F2vjiqsmqaSN5aSxQQXZXMKN01SCTHd6D2vXH9WvVdE5T5mYIBuzgUoeAAA",
    alt: "High-rise building under construction with scaffolding",
    source: unsplash("1632398461363-741a64493ab6"),
  },
  farmShed: {
    src: "/images/farm-shed.webp",
    width: 1920,
    height: 1282,
    blur: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAgCdASoMAAgAA4BaJagCdGuA/gAFuYmUgAD8jwUeNq/Aat7AUBuWQhviK7p+ibtajXssdvXylnrewdMAAA==",
    alt: "Steel-clad agricultural shed beside a field",
    source: unsplash("1587563497254-d04841987d8e"),
  },
  metroViaductIndia: {
    src: "/images/metro-viaduct-india.webp",
    width: 1920,
    height: 2560,
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoMABAAA4BaJYwCw7Ywm7k91jAA/ptqlm8Qrt3WEGrTSdp6Bn6zqN0sZyO01MVpRhK3veMeohr0tEp1UuBeftMSD8Kq9N/pIACxpiKLs+Up+UWhGPspTKVdjEvPcopQAAA=",
    alt: "Elevated metro viaduct in an Indian city",
    source: unsplash("1594383274581-86711b1c4265"),
  },
  metroIndiaCity: {
    src: "/images/metro-india-city.webp",
    width: 1920,
    height: 1602,
    blur: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAAoAA4BaJYwC7ADdc3GdZEAA/o+pce9IFWHX/aEa+l/2suSOC4yoCmejWCAA",
    alt: "Elevated metro line crossing an Indian cityscape",
    source: unsplash("1648455288365-ee27a61c95bd"),
  },
  cranesBuilding: {
    src: "/images/cranes-building.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAgAA4BaJZQAApumOTsgAP7eNbnvljlJrqayQcVQev/MuPFk33YgJdxBNtQgAAA=",
    alt: "Tower crane beside a building under construction",
    source: unsplash("1599707254554-027aeb4deacd"),
  },
  siteAerialRebar: {
    src: "/images/site-aerial-rebar.webp",
    width: 1920,
    height: 1280,
    blur: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAgAA4BaJZwAAmejR9jgAPulFPDcBslxmwsRv1tgXlQhJ3hwDQeTDJci6yBgAAA=",
    alt: "Aerial view of engineers on a reinforced concrete site",
    source: unsplash("1541888946425-d81bb19240f5"),
  },
  giPipesBundles: {
    src: "/images/gi-pipes-bundles.webp",
    width: 1920,
    height: 1476,
    blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABQAgCdASoMAAkAA4BaJYwCdAYtVzekFnI4y+AA/OXiARSf4KO7Bnr93VcGj9/S8uIHvt2AwTGs2kd99o5/ESaH8yo5KzTyj/IbXdgA",
    alt: "Bundles of galvanised steel pipes",
    source: { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:Steel_pipe.jpg", author: "Sắt Thép Biên Hòa", license: "CC BY-SA 4.0" },
  },
  ibeamsYard: {
    src: "/images/ibeams-yard.webp",
    width: 1920,
    height: 1080,
    blur: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoMAAcAA4BaJZACdADbUfAAAP7pAI61ff18WSfekYItKtBBf50TPg/IuQR15QU91cGgPugAU8XbeI0t61fNfKNt9ggAAA==",
    alt: "Steel I-beams stored in a fabrication yard",
    source: { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:I-beam_raw_material_at_WP_Welding_3.jpg", author: "W.carter", license: "CC0" },
  },
  giCoilsStack: {
    src: "/images/gi-coils-stack.webp",
    width: 1920,
    height: 1440,
    blur: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAkAA4BaJYwCdAEPMsOQAP6ZQwPvnz7DPq/jztq4JYf8UlhRv2axF4Z0RP069L5En8uUwSqM1EAA",
    alt: "Stacked galvanised steel coils in a stockyard",
    source: { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:Leeco_Steel_Trading_-_GI_coils.jpg", author: "Arosset", license: "CC BY-SA 4.0" },
  },
  pebFrame: {
    src: "/images/peb-frame.webp",
    width: 1920,
    height: 910,
    blur: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABQAgCdASoMAAYAA4BaJZwCdH8AF8uCUhYA8AAA/fgugHTQM820WJqVs1BcVxJZIEy1F0AA",
    alt: "Pre-engineered steel building frame under construction",
    source: { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:Q345B_Steel_Frame.jpg", author: "Syibeehive", license: "CC BY-SA 4.0" },
  },
  bridgeTrussIndia: {
    src: "/images/bridge-truss-india.webp",
    width: 1920,
    height: 1290,
    blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAAgAA4BaJZQCdADdqzqhH4AA/uiCLBz+e0I9qVMUX5s1Um0mtg/TcO9jIUxJ616yWumXbpKIOiOFrTDNGm6XSifkgAAA",
    alt: "Vivekananda Setu steel truss bridge, Kolkata",
    source: { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:Vivekananda_Setu_(Bali_Bridge).jpg", author: "Biswajit Das", license: "CC BY 2.0" },
  },
  steelPlantLadle: {
    src: "/images/steel-plant-ladle.webp",
    width: 1600,
    height: 1069,
    blur: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoMAAgAA4BaJagCdAEf3ax1YkaAAP7psIEd7Sq+ops2RMEwBXWJ1Ys2EN3zXVDcVjFxg3+Zr632+ODHhKOcREhgAAA=",
    alt: "Molten steel being poured at an Indian steel plant",
    source: { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/File:Furnace_of_IISCO_Steel_Plant-2.jpg", author: "IISCO Steel Plant", license: "GODL-India" },
  },
} satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof images;

export const img = (key: ImageKey): SiteImage => images[key];

/**
 * Stockyard gallery. Currently uses representative photography of the product
 * families held in stock. Replace or prepend with the client's own stockyard
 * photographs (register them in `images` above) for maximum authenticity.
 */
export const stockyardGallery: { key: ImageKey; label: string }[] = [
  { key: "structuralSectionsWarehouse", label: "Structural sections" },
  { key: "pipesRustyStack", label: "MS pipes" },
  { key: "stockRacksBars", label: "Bars & flats" },
  { key: "coilsWarehouse", label: "Coils" },
  { key: "tmtBarsStack", label: "TMT bars" },
  { key: "ibeamsYard", label: "Beams" },
  { key: "giPipesBundles", label: "GI pipes" },
  { key: "stockRacksFlats", label: "Flats" },
  { key: "sheetsCoatedStack", label: "Sheets" },
  { key: "tmtCoils", label: "Reinforcement coils" },
];
